version: "3.8"

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: nestJs-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Password_2547422
      MYSQL_DATABASE: nestJs
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # NestJS Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: nestJs-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Password_2547422
      DB_NAME: nestJs
      DB_SYNCHRONIZE: false
      JWT_SECRET: secret
      JWT_TOKEN_EXPIRY: 1h
      JWT_REFRESH_SECRET: secret
      JWT_REFRESH_EXPIRY: 7d
      RATE_LIMIT_TTL: 60
      RATE_LIMIT_LIMIT: 100
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Adminer for Database Management (Optional)
  # adminer:
  #   image: adminer:4.8.1
  #   container_name: nestJs-adminer
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mysql
  #   environment:
  #     ADMINER_DEFAULT_SERVER: mysql

volumes:
  mysql_data:
    driver: local

networks:
  default:
    name: nestJs-network
